Expose collection metadata API documentation with Swagger
OpenTermsArchive/engine pull request #1015
Opened 2023-07-04 14:16 UTC by Ndpnt

2023-07-04 17:10 UTC, MattiSG commented on package.json
> +    "swagger-ui-express": "4.6.2",
Why is this version locked? 🤔

2023-07-04 17:11 UTC, MattiSG commented on CHANGELOG.md
> +- Expose collection metadata API documentation with a user-friendly interface
Let's avoid judgement (even positive) in our changelog.

```suggestion
- Embed [Swagger UI](https://swagger.io) for graphical user interface documentation of the API
```

2023-07-05 06:53 UTC, Ndpnt commented on package.json
> +    "swagger-ui-express": "4.6.2",
Because the version 4.6.3 is broken

2023-07-05 08:07 UTC, MattiSG reviewed
I get a blank page if I navigate to `http://localhost:3000/api/v1/docs/` after having run `npm install` and `npm start:api`.

2023-07-05 08:08 UTC, MattiSG commented
(also, the server does not echo the URL, which would be useful, but that's out of scope I guess)

2023-07-05 08:11 UTC, Ndpnt commented
> I get a blank page if I navigate to `http://localhost:3000/api/v1/docs/` after having run `npm install` and `npm start:api`.

Hum weird 🤔. I have the same error as you with Safari but it works with Chrome and Firefox.

2023-07-05 08:20 UTC, Ndpnt commented
Ok, I found why. It's related to the way browsers handle `upgrade-insecure-requests directive`. 
See https://github.com/helmetjs/helmet/issues/429#issuecomment-1599789358:
> Chrome and Firefox don't think that localhost needs "upgrading" from HTTP to HTTPS, but Safari does.

2023-07-05 14:36 UTC, Ndpnt commented
I fix the issue on Safari and I also change the Swagger UI url to `/` instead of `/docs` to load the Swagger UI docs by default.

2023-07-05 14:40 UTC, Ndpnt commented
I tried the deployment on the experimentation server, you can check the Swagger UI here: http://54.37.5.206/api/v1/

2023-07-10 15:09 UTC, MattiSG commented on src/api/routes/docs.test.js
> +        it('openapi version', () => {
```suggestion
        it('OpenAPI version', () => {
```

2023-07-10 15:13 UTC, MattiSG commented on src/api/routes/index.js
> +    res.json({ message: 'Welcome to an instance of the Open Terms Archive API. Documentation is available at /docs' });
```suggestion
    res.json({ message: 'Welcome to an instance of the Open Terms Archive API. Documentation is available at /docs. Learn more on Open Terms Archive on https://opentermsarchive.org.' });
```

2023-07-10 15:17 UTC, MattiSG commented on CHANGELOG.md
> +- Embed [Swagger UI](https://swagger.io) for graphical user interface documentation of the API
I believe we are missing some breaking changes announcements, don't we? 🙂

2023-07-10 15:39 UTC, MattiSG requested changes

2023-07-10 15:39 UTC, MattiSG commented on CHANGELOG.md
> +- Change path from `/services/:serviceId` to `/service/:serviceId` for direct access to a `service` resource; update paths accordingly in your own codebase
Always put breaking changes on top (before additions).
```suggestion
- **Breaking** Change path from `/services/:serviceId` to `/service/:serviceId` for direct access to a `service` resource; update paths accordingly in your own codebase
```

2023-07-10 15:39 UTC, MattiSG commented on CHANGELOG.md
>  - Embed [Swagger UI](https://swagger.io) for graphical user interface documentation of the API
> Was the OpenAPI documentation already there before this changeset? 🤔 Didn't it move from `specs` to `docs`?

2023-07-10 15:52 UTC, MattiSG approved these changes
🎉 Perfect!!

2023-07-10 15:52 UTC, MattiSG commented on CHANGELOG.md
> +- Embed [Swagger UI](https://swagger.io) for graphical user interface documentation of the API
```suggestion
- Embed [Swagger UI](https://swagger.io) for graphical user interface documentation of the API; access it on `/docs`
```

2023-07-10 16:04 UTC, merged