Expose versions data through the collection API
OpenTermsArchive/engine pull request #1033
Opened 2023-12-06 15:37 UTC by Ndpnt

2023-12-08 12:04 UTC, MattiSG requested changes

2023-12-08 12:04 UTC, MattiSG commented on src/api/routes/versions.test.js
> Thanks! The test classes seem relevant to me 🙂 
>
> I personally would support a slightly more terse version of those tests where we would test in a single `it` block that the status code, the content-type and the content are as the expected ones. The current approach is certainly more precise and enables exact pinpointing of potential issues. However, those tests are also expensive to create and maintain (see for example here the mistake in some test descriptions). I would not see a problem decreasing the quality by grouping those tests and having less description text to maintain 🙂
>
> This is not a request for changes.

2023-12-11 08:48 UTC, Ndpnt commented on CHANGELOG.md
> +- Expose versions data through the collection API ([#1003](https://github.com/OpenTermsArchive/engine/pull/1028))
Explain the precondition: commit date must be equal to author date

2023-12-11 08:51 UTC, Ndpnt commented on src/api/server.js
> +if (process.env.NODE_ENV !== 'test') {
Event when testing the server is started, there is only no server log to avoid polluting the test log.

2023-12-11 10:13 UTC, Ndpnt commented on src/api/routes/versions.js
> + *         description: The ID of the service.
`externalDocs` cannot be used for query params

2023-12-11 13:41 UTC, merged