Refactor GitLab integration
OpenTermsArchive/engine pull request #1116
Opened 2024-11-06 15:26 UTC by Ndpnt

Thanks @alessandrozago to the work done in #1098 to support GitLab as an alternative to GitHub for both issue reporting and dataset publishing. 🎉

This PR refactors the initial implementation to reduce the code footprint needed to support GitLab and improve overall consistency across the codebase. 

@MattiSG, could you please review these changes first? Once reviewed, we’ll ask @alessandrozago to perform additional testing with GitLab to confirm everything works as expected and offer any feedback.

2024-11-07 09:14 UTC, MattiSG requested changes
I reviewed the disjunction code and the metadata. I didn't review the GitHub and GitLab detailed code and didn't test it.

2024-11-07 09:14 UTC, MattiSG commented on scripts/dataset/publish/index.js
> +    return publishGitHub({ archivePath, releaseDate, stats });
I would find it important to document either through a message here or in the README that `OTA_ENGINE_GITHUB_TOKEN` takes precedence over `OTA_ENGINE_GITLAB_TOKEN` if both are defined 🙂

2024-11-08 08:30 UTC, alessandrozago commented
Dear all, thank you for your interest in this GitLab integration.
We would like to ask to restore the GitLab URL setting in the .env configuration file, since now the URL is hardcoded (mainly `OTA_ENGINE_GITLAB_BASE_URL`, while `OTA_ENGINE_GITLAB**_API**_BASE_URL` could be built by simply adding the '/api/v4' hardcoded).
This is useful because GitLab allows to set up custom instances, with different URLs/domains. This also our real use case with the repository: https://code.europa.eu/p2b .
Would you agree in putting the setting back in the code?
Please let us know. Thank you

2024-11-08 08:31 UTC, alessandrozago commented on CHANGELOG.md
> +
Hi @MattiSG , thank you for the support. For the contribution we would like to have "European Union" as text and "https://commission.europa.eu/" as the link.
Please let us know if there is any issue.

2024-11-12 16:08 UTC, Ndpnt commented
Related documentation update https://github.com/OpenTermsArchive/docs/pull/147

2024-11-12 16:09 UTC, Ndpnt commented
@alessandrozago Could you please confirm that it works as expected with GitLab?

2024-11-12 16:40 UTC, alessandrozago commented
> @alessandrozago Could you please confirm that it works as expected with GitLab?

Hi @Ndpnt , we did some preliminary testing on the version of commit aed17f3, and the only issue we found at the moment is that the code still references the old parameter "versionsRepositoryURLGitLab" instead of the generic "versionsRepositoryURL".
This occurs in: 
- scripts/dataset/publish/gitlab/index.js:23 and :104
I just saw the updated documentation that mentions only one parameter "versionsRepositoryURL".
Please let me know if I should notify this issue in any other way.

When fixed we are available to test it again with also the latest changes from today's commits. Thank you

2024-11-13 08:29 UTC, MattiSG commented on src/reporter/index.test.js
> +          }).to.throw('Required configuration key "reporter.repositories.declarations" was not found; issues on the declarations repository cannot be created');
> I recommend checking against just a significant subset of the string rather than the entire error message, to maximise tests maintainability.

2024-11-13 08:29 UTC, MattiSG commented on src/reporter/index.js
> +   * Support for legacy config format where reporter configuration was nested under "githubIssues"
```suggestion
   * Support for legacy config format where reporter configuration was nested under `githubIssues`
```

2024-11-13 08:47 UTC, Ndpnt commented
@alessandrozago Could you also review the [documentation update PR](https://github.com/OpenTermsArchive/docs/pull/147) to ensure it’s clear and reflects the recent GitLab updates?

2024-11-13 14:21 UTC, alessandrozago commented
> > > @alessandrozago Could you please confirm that it works as expected with GitLab?
> > 
> > 
> > Hi @Ndpnt , we did some preliminary testing on the version of commit [aed17f3](https://github.com/OpenTermsArchive/engine/commit/aed17f341523d3686aa819e2c7e1dd7947114d67), and the only issue we found at the moment is that the code still references the old parameter "versionsRepositoryURLGitLab" instead of the generic "versionsRepositoryURL". This occurs in:
> > 
> > * scripts/dataset/publish/gitlab/index.js:23 and :104
> >   I just saw the updated documentation that mentions only one parameter "versionsRepositoryURL".
> >   Please let me know if I should notify this issue in any other way.
> > 
> > When fixed we are available to test it again with also the latest changes from today's commits. Thank you
> 
> Thank you for your feedback! I’ve addressed the issue regarding the old parameter "versionsRepositoryURLGitLab" in the code. The references have been updated to use the generic "versionsRepositoryURL" as per the latest documentation.
> 
> Feel free to test again with today's latest commits. Let me know if anything else comes up!

Hi @Ndpnt , thanks for the fix on the parameter.
We have tested the latest version of the code ( 0bdd637 ), and it seems to run correctly. We found one error analyzing the logs:
"Error in "Reporter" plugin: TypeError: this.reporter.clearCache is not a function" on /src/reporter/index.js:91 .
The cache was only introduced for github in OTA version 2.3.3, and is not present in the gitlab code we wrote. Aside from the error in the logs, everything else seems to work as expected.

Another small thing is that I left a logger line on debug level with no real indication for the final user ( /src/reporter/gitlab/index.js:265 ). I can remove it on my fork (or change the message to something more clear) but this pull request does not seem to be linked, so it should not update the code. Please let me know if I should do some action to help on this.

We did not find any other issues that can impact the functionalities. So, aside from the error on the cache mentioned above, on our side it is ok to proceed. Please let us know if you would like any other action from our side.

2024-11-13 16:32 UTC, Ndpnt commented
Thanks @alessandrozago for the valuable tests!

2024-11-18 10:48 UTC, MattiSG approved these changes

2024-11-18 10:48 UTC, MattiSG commented on scripts/dataset/publish/index.js
> +  throw new Error('No GitHub or GitLab token found in environment variables (OTA_ENGINE_GITHUB_TOKEN or OTA_ENGINE_GITLAB_TOKEN). Cannot publish the dataset without authentication.');
```suggestion
  throw new Error('No GitHub nor GitLab token found in environment variables (OTA_ENGINE_GITHUB_TOKEN or OTA_ENGINE_GITLAB_TOKEN). Cannot publish the dataset without authentication.');
```

2024-11-19 08:41 UTC, merged